### ISSUE TITLE
Use SonarQube.com for quality analysis

### ISSUE THREAD

**Issue by mvitz** [liquigraph/liquigraph#116]
Maybe it would be worth trying to gather some analysis data using SonarQube.com

See https://about.sonarqube.com/news/2016/09/01/sonarqubedotcom-open-to-aynone.html

**Comment by fbiville** [comment]
Funny, I just talked about it with @fpavageau yesterday :D

**Comment by fbiville** [comment]
Done via https://github.com/liquigraph/liquigraph/commit/86eb4d087c2d996982cf3dab726a514376ffe20a
