### ISSUE TITLE
[Support request] Running groovy scripts

### ISSUE THREAD

**Issue by mburak** [liquigraph/liquigraph#151]
Is running groovy scripts on a changeset (instead of just cypher) allowed? Or are you planning to include this feature?

**Comment by fbiville** [comment]
Hi, thanks for opening an issue and happy new year!
By Groovy script, do you mean https://github.com/tinkerpop/gremlin?
This could be a good user story.

IIRC, Gremlin is not supported out of the box in Neo4j, or?

**Comment by fbiville** [comment]
Actually, I I see two scenarios:

1. supporting Gremlin for Neo4j migrations
1. supporting Gremlin for all kinds of "Tinkerpop graph DBs"

The first one seems a bit like a niche to me: the trend for Neo4j is to focus on Cypher.
The second one is much more interesting but also much bigger and more complex.

Did you have anything like that in mind?

**Comment by mburak** [comment]
Hi, thanks for your quick reply!
Actually I was thinking about more generic groovy scripts like what it's provided in these projects:
- https://github.com/grails-plugins/grails-database-migration
- https://grails.org/plugin/groovations

The use case is basically that sometimes just doing a cypher query is not enough for a migration and we need more logic that depends on the business model, so i.e. you need to retrieve some stuff then do some manipulation and then execute some cypher on a loop. Our project is in Grails so i was expecting to have some variables available while executing a script, like having the application context or the db abstraction layer so instead of using cypher you just can use java/groovy.
Does that makes sense?

**Comment by fbiville** [comment]
@mburak I see.
The best bet for now is to directly use Liquigraph Core API and programmatically define migrations this way. Maybe that can integrate with grails-database-migration, but that would require some initial exploration. If you're willing to dig into that, your help is most welcome! :-)

**Comment by fbiville** [comment]
Not actively working on this issue right now, so I'll close it.
Let's reopen it if other people express the same needs or a PR shows up :)
