### ISSUE TITLE
[Core] Add logging to understand what's going on

### ISSUE THREAD

**Issue by fbiville** [liquigraph/liquigraph#155]
There should be some logs indicating what's going on when the migrations are running. 
This would definitely help end users.

**Comment by geld0r** [comment]
Any progress on this?
I've recently encountered several cases where my app is hanging on startup which I believe is due to liquigraph (probably while trying to lock the DB). Since there is nothing in the logs, this is hard to investigate...

**Comment by fbiville** [comment]
Hi, thanks for the reminder. We're currently working on infrastructure and did not get back to this issue.

Would you like to submit a PR or review one? This should not require too much effort.

This is an important one, we'll try to push something asap otherwise.

**Comment by fbiville** [comment]
@geld0r sorry to resurrect an old discussion, but some work has been done now and merged into master. Feel free to check https://github.com/liquigraph/liquigraph/commit/fa9d07e1836bc7dd98f981fc0b6e21c6920fe151 and reopen this issue if you think some important details have been left out.
