### ISSUE TITLE
[Spring Boot Starter] Support for execution contexts

### ISSUE THREAD

**Issue by benoutram** [liquigraph/liquigraph#181]
With the Spring Boot Starter, migrations are run automatically at startup. It doesn't appear possible to control execution contexts at the moment resulting in all contexts being run.

**Comment by fbiville** [comment]
Thanks for the report, let us think about a good approach to configure this 👍

**Comment by fbiville** [comment]
@benoutram would you be willing to submit a pull request? The additions should be quite straightforward and we can help!

**Comment by fbiville** [comment]
Working on it now.

 - [ ] Fixing the unused `liquigraph.enabled` flag to disable Liquigraph automatic start.\
 - [ ] Allow the configuration of execution modes (dry-run vs. run). While run remains the default, dry-run can be interesting in tests.
 - [ ] Allow the configuration of execution contexts.

**Comment by mvitz** [comment]
@fbiville although it seems the `liquigraph.enabled` flag is never used it is actually referenced in `LiquigraphAutoconfiguration` (https://github.com/liquigraph/liquigraph/blob/5492eeab1c24ea39ad6978bb2b2eee395adc486d/liquigraph-spring-boot-starter/src/main/java/org/liquigraph/spring/starter/LiquigraphAutoConfiguration.java#L43). If is it set to `false` the complete auto configuration is ignored and therefore no `SpringLiquigraph`-Bean is created.

**Comment by fbiville** [comment]
Oh, good catch! I somehow completely missed the line :)

**Comment by fbiville** [comment]
I think I'll solely focus on execution contexts for now as the execution mode support may require some changes in Liquigraph core, this will be filed in another issue.

**Comment by fbiville** [comment]
Merged in 782e7d65f52968bd1b78841e7017c9faa21e2f4c.
