### ISSUE TITLE
Allow to configure Migration with embedded GraphDatabaseService instace

### ISSUE THREAD

**Issue by aillusions** [liquigraph/liquigraph#185]
I'm instantiating neo4j in my app's JVM

```
GraphDatabaseFactory graphDbFactory = new GraphDatabaseFactory();
GraphDatabaseService graphDb = graphDbFactory.newEmbeddedDatabase("/path/to/data");

```
So there is no DataSource or JDBC URL to be able to configure Liquigraph migration, which only accept one of those. 

Can we have something like 

```
Configuration configuration = new ConfigurationBuilder()
                .withMasterChangelogLocation("neo4j_changelog.xml")
                .withDbInstance(graphDb)
                .build();

Liquigraph liquigraph = new Liquigraph();
liquigraph.runMigrations(configuration);
```

Thanks

**Comment by fbiville** [comment]
Hello, what version of Neo4j are you using?
If you are using Neo4j 2.x, you already can: https://github.com/liquigraph/liquigraph/blob/2.x/liquigraph-core/src/main/java/org/liquigraph/core/configuration/ConfigurationBuilder.java#L106

**Comment by fbiville** [comment]
Closing this now. Feel free to reopen if you don't find the previous answer satisfactory.
