### ISSUE TITLE
Spring Boot 2 support

### ISSUE THREAD

**Issue by Artgit** [liquigraph/liquigraph#192]
Hi!

First of all, thank you very much for your awesome work! 

I have a question - do you support Spring Boot 2 for `liquigraph-spring-boot-starter` ?

Thanks.

**Comment by fbiville** [comment]
Hi, 

That's a great question. I'm not sure, we have not tested it yet.
@mvitz what do you think?

**Comment by mvitz** [comment]
As far as I am aware they did not change anything regarding the auto configuration. Therefore it should be possible to use this starter with Spring Boot 2.

**Comment by fbiville** [comment]
@Artgit feel free to try Spring Boot 2
You can look at our own Spring Boot 1.5 example as a starting point (https://github.com/liquigraph/liquigraph/tree/master/liquigraph-examples/spring-boot)
