### ISSUE TITLE
Repository with stable version

### ISSUE THREAD

**Issue by igler** [liquigraph/liquigraph#194]
Is there a repository I can integrate into pom.xml where a stable version of `liquigraph-spring-boot-starter` is hosted?

**Comment by fbiville** [comment]
Hi, we have not released the Spring Boot starter yet, as there were some blocker issues.
The good news is that these issues should be solved soon and therefore we will be able to produce a new release soon as well.

**Comment by igler** [comment]
Cool, looking forward to stable release! BTW, great work!

**Comment by fbiville** [comment]
@igler Liquigraph 3.0.2 (with Spring Boot!) has been released today!
