### ISSUE TITLE
zip, tar.gz, and tar.bz2 links do not work in the latest version of the documentation

### ISSUE THREAD

**Issue by ihatemundays** [liquigraph/liquigraph#207]
I tried downloading the standalone liquigraph component from the [help page](http://www.liquigraph.org/latest/index.html), and it can't be found in the maven repository.

I stepped back one less version in the [documentation](http://www.liquigraph.org/3.0.x/index.html), and I noticed that those links do work.

It looks to just be a link reference error.

**Comment by fbiville** [comment]
Hi, 

Thanks a lot for the report! I'll fix the versions in the links, unless you want to submit a pull-request on [the documentation](https://github.com/liquigraph/liquigraph.github.io/blob/master/latest/index.html)? :)

**Comment by fbiville** [comment]
It should be fixed now, thanks for reporting!
