### ISSUE TITLE
How do you remove all liquigraph from neo4j

### ISSUE THREAD

**Issue by MazizEsa** [liquigraph/liquigraph#217]
I want to remove all liquigraph traces from neo4j so the next time it's being run it will recognize as new db.
How it should be done?

**Comment by MazizEsa** [comment]
Yeah precisely. And any traces of liquigraph.

**Comment by fbiville** [comment]
Note/disclaimer to future readers: this is an implementation detail of Liquigraph and is subject to change. Following the instructions below are not guaranteed to work. Do it at your own risk.

You can run something like:
```
MATCH (changelog:__LiquigraphChangelog), (changesets:__LiquigraphChangeset), (changesetQueries:__LiquigraphQuery), (lock:__LiquigraphLock)
DETACH DELETE changelog, changesets, changesetQueries, lock
```

May I know why you need to remove Liquigraph? Did something unexpected happen?

**Comment by MazizEsa** [comment]
No nothing wrong. I wanted to remove so that I can reapply again on places that you can't remove the file in neo4j.

What about the index and the constrain?

**Comment by fbiville** [comment]
There is only one index/constraint: a unicity constraint is set on `__LiquigraphLock`.

**Comment by MazizEsa** [comment]
Ah so i guess you just need ot run these right?

> match (n) where n:__LiquigraphLock or n:__LiquigraphQuery or n:__LiquigraphChangelog or n:__LiquigraphChangeset detach delete n
> drop constraint on (__liquigraphlock:__LiquigraphLock ) ASSERT __liquigraphlock.name IS UNIQUE

**Comment by fbiville** [comment]
Exactly, you can run these once, targetting the database you are running Liquigraph on.

**Comment by MazizEsa** [comment]
Got it thanks. Maybe should put this in doc somewhere? @fbiville

**Comment by fbiville** [comment]
@MazizEsa this is very tied to the implementation of Liquigraph and I am not willing to publish these as if it was a public API.

However, I agree there is a need to have a way to clean up the history graph. Maybe we could implement an extra command like : `liquigraph remove-all` or something like that (whether with Liquigraph core, Liquigraph Maven plugin or Liquigraph shell).

Let me open an issue about that and thanks a lot for opening this issue!
