### ISSUE TITLE
Fix build with JDK 11

### ISSUE THREAD

**Issue by fbiville** [liquigraph/liquigraph#226]

**Comment by fpavageau** [comment]
Do we need to build with JDK 11? Run it, sure, but why build it? We'd need a Java 8 target, and a check of the API used to be sure we don't call new methods.

**Comment by sey** [comment]
I know you closed the issue yesterday, but I think it should remain open.

As of Neo4j 4.0, the JDK 11 is required.  
I'm not an expert of what would be the best strategy to support Neo4j below 4.0 with JDK 8 and Neo4j 4.0 and above with JDK 11.  
I'm working on an app which targets Neo4j 3.5 at the moment but we are going to have a Neo4j 4.0 cluster. 
So I'm currently testing that app against Neo4j 4.0 (with Liquigraph and I just hit a wall).  
I will try today to build Liquigraph with JDK 11. I already have a fully working build with JDK 11 of the Neo4j JDBC driver. 
Depending on what I find, I will try to contribute back to the project.

**Comment by fbiville** [comment]
@sey let's open an issue for Neo4j 4.0 support, as this will most likely require a new branch (or rather, `master` will become `3.x` and the new `master` will be for Neo4j 4.x).
This initial issue was about supporting JDK 11 for Liquigraph 3.x (/Neo4j 3.x) which does not make sense.

**Comment by fbiville** [comment]
Here is it (mostly as a placeholder atm) https://github.com/liquigraph/liquigraph/issues/257
Feel free to post the "walls" you hit there.
