### ISSUE TITLE
Spring boot app never closes (Bolt + Hikari)

### ISSUE THREAD

**Issue by lio955** [liquigraph/liquigraph#227]
With the 3.4.0 neo4j driver on a bolt url and using Hikari CP as described in the 5minutes guide, the spring boot app never ends.

**Comment by fbiville** [comment]
Hi, thanks for the report.
Would you have a sample app that one can test?

**Comment by fbiville** [comment]
Closing for now because of lack of details. Happy to re-open it once we know more about the situation.
