### ISSUE TITLE
Support for JanusGraph 

### ISSUE THREAD

**Issue by mad** [liquigraph/liquigraph#239]
JanusGraph has schema configuration API https://docs.janusgraph.org/latest/schema.html

**Comment by fbiville** [comment]
Hi and thanks for opening this issue.

That is interesting but given Liquigraph is at the moment tightly coupled to Cypher as a query language, I am not sure how much it would require to support another graph database.

Does JanusGraph support (open)cypher?
Does JanusGraph support transactions?

**Comment by mad** [comment]
Hi

JanusGraph backed by [tinkepop](http://tinkerpop.apache.org/) and support [gremlin query](https://docs.janusgraph.org/latest/gremlin.html) as main query language. Possibly, may use [cypher-for-gremlin](https://github.com/opencypher/cypher-for-gremlin) for some changes

JanusGraph support low level schema configuration like a property datatype/cardinality/renaming, index building and so on, through its internal API [JanusGraphManagement](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java#L33). This API not supported by cypher-for-gremlin

Yes, janusgraph support [transactions](https://docs.janusgraph.org/latest/tx.html)

**Comment by fbiville** [comment]
If someone is interested in implementing the support, I'm happy to offer guidance. Closing the issue for now.
