### ISSUE TITLE
[core] Using Liquigraph offline

### ISSUE THREAD

**Issue by mattharr** [liquigraph/liquigraph#241]
Hi,
We're using Neo4j, and so I was looking at using liquigraph to manage the database.  I'd got it up and running fine on my machine, but when I tried on the server I got the following in the log:

> 12:05:39.756 INFO  [main] n.g.l.m.i.neo4j.LiquigraphRunner – Running liquigraph migration
12:07:27.493 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.494 ERROR [main] o.l.core.io.xml.ChangelogParser – XSD validation error : cvc-elt.1.a: Cannot find the declaration of element 'changelog'.
12:07:27.501 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.501 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.502 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.502 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.503 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.503 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.504 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.504 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.505 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
12:07:27.505 WARN  [main] o.l.core.io.xml.ChangelogParser – XSD validation warning : schema_reference.4: Failed to read schema document 'http://www.liquigraph.org/schema/1.0/liquigraph.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
java.lang.IllegalArgumentException: 
	cvc-elt.1.a: Cannot find the declaration of element 'changelog'.
	at org.liquigraph.core.io.xml.ChangelogParser.parseChangelog(ChangelogParser.java:67)

I think this is because it has no internet access, and I get the same on my machine if I turn off the wifi.

My migration file looks like this:
`<?xml version="1.0" encoding="UTF-8"?>
<changelog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://www.liquigraph.org/schema/1.0/liquigraph.xsd">
    <changeset id="1" author="matth">
        <query>...</query>
        <query>...</query>
        <query>...</query>
    </changeset>
    <changeset author="matth" id="2">
    	<query>..</query>
    </changeset>
</changelog>`

I had a look around, and thought that removing the noNamespaceSchemaLocation declaration would kick it over to the ImplicitSchemaValidator, and then it would use the XSD in the jar file (from the classpath).  But I've been having a try at getting this working, and can't.  I've tried adding namespaces in, but had no luck.
Does anyone have any pointers on how to get liqiugraph running offline?

Thanks in advance for any help,

Matt

**Comment by mattharr** [comment]
I should say, without the noNamespaceSchemaLocation attribute, I get the following error:

> 12:21:17.113 INFO  [main] n.g.l.m.i.neo4j.LiquigraphRunner – Running liquigraph migration
12:21:28.005 ERROR [main] o.l.core.io.xml.ChangelogParser – XSD validation error : cvc-elt.1.a: Cannot find the declaration of element 'changelog'.
java.lang.IllegalArgumentException: 
	cvc-elt.1.a: Cannot find the declaration of element 'changelog'.
	at org.liquigraph.core.io.xml.ChangelogParser.parseChangelog(ChangelogParser.java:67)
	at org.liquigraph.core.io.xml.ChangelogParser.parse(ChangelogParser.java:59)
	at org.liquigraph.core.api.MigrationRunner.parseChangesets(MigrationRunner.java:87)
	at org.liquigraph.core.api.MigrationRunner.runMigrations(MigrationRunner.java:68)

**Comment by fbiville** [comment]
Hi, thanks for the report.
You raise a very good point, the schema not being reachable should not block Liquigraph.
Would you be interested in submitting a patch? I can guide you through the codebase.

**Comment by mvitz** [comment]
Some hints for resolving this:

For Java SAX Parsers a custom `org.xml.sax.EntityResolver` can be registered (via `setEntityResolver`) that is responsible for retrieving the schema that will be used for validation.

Spring already solved the same kind of problem with their own `EntityResolver` (see https://github.com/spring-projects/spring-framework/blob/3a0f309e2c9fdbbf7fb2d348be861528177f8555/spring-beans/src/main/java/org/springframework/beans/factory/xml/PluggableSchemaResolver.java#L109-L138).

The four schema URIs currently used in the liquigraph tests are:
* http://www.liquigraph.org/schema/1.0/liquigraph.xsd
* http://www.liquigraph.org/schema/1.0-RC3/liquigraph.xsd
* https://fbiville.github.io/liquigraph/schema/1.0/liquigraph.xsd
* https://fbiville.github.io/liquigraph/schema/1.0-RC3/liquigraph.xsd

Maybe these hints helps someone getting started.

**Comment by mattharr** [comment]
Hi,

I will try have a look into it.  I have forked it, and pulled it down to have a look, but got some test failures - maybe because I'm on Windows(?) but I'll have a look.

In terms of making the change, in the first instance should I look at the ExplicitSchemaValidator?  Why the Implicit and Explicit Validators?  I guess both need fixing up?  Then I'll add all the schema definitions in to the classpath.  Does that sound reasonable?  Then I'll have a hunt round and follow on from there?

Any thoughts or advice let me know, and I'll see how I get on.

Cheers,

Matt

**Comment by fbiville** [comment]
@mattharr As far as I remember, the `Implicit` instance was introduced for backwards compatibility, as the first Liquigraph versions did not work with a schema and we wanted to continue to support that.

Regarding the Windows errors, that is something we do not monitor frequently enough (maybe we can update our Travis CI to run on Windows) and there may be build errors indeed, sorry about that!
 
I'd say: start with the `Explicit` one and `http://www.liquigraph.org/schema/1.0/liquigraph.xsd`.

Thanks a lot for looking into it!

**Comment by mattharr** [comment]
Hi,

I had a go at a first pass: https://github.com/mattharr/liquigraph/commit/ac7d953355d9dd105c44ccc7fc8ec9212805e339

I ended up commenting out the tests that didn't pass for me - I'll look to circle back and have a look at them at some point if its worth getting them going again?  (need to brush up on my regex).

I ended up only adding the one xsd, as I found that that passed all the tests, and got my changelog working offline - but I guess the others may be needed for backwards compatibility?  Or is it not an issue, as anyone using the older xsds must be using them online, therwise they wouldn't be working?

The EntityResolver is very simplistic, so happy to change if it could do with a bit more done to it.

I'm going to be on holiday next week, so will not be online much.  Feel free to push this on, or leave comments for me to have a look at when I get back.

Cheers,

Matt

**Comment by fbiville** [comment]
@mvitz would you be available to follow that issue and help @mattharr? you are definitely more knowledgeable than me on this topic :)

**Comment by mvitz** [comment]
I'll try to find some time this week.

**Comment by fbiville** [comment]
FYI I fixed a bunch of issues in https://github.com/liquigraph/liquigraph/pull/242. I'll merge them when I land.

**Comment by mvitz** [comment]
@mattharr your change seems reasonable to me.

I'm not sure what to do in regards to backwards compatibility but I think it would be ok to wait until someone with an older schema happens to have the same issue with offline capability.

It would be nice if you could rebase your branch against the current `master` and try if the tests are now passing.

**Comment by mattharr** [comment]
Hi,

Will do.  Meant to follow up on this, but didn't get round to it, but this
will be key for me being able to use liquigraph.  I'll rebase over the next
week, and let you know how I get on.

Cheers,

Matt

**Comment by mattharr** [comment]
Hi, 
One of the changes made was to add and use a RedirectAwareEntityResolver, which I guess is useful if resolving over HTTP; but given this change is just looking to resolve from the local file system, do we get rid of that change?  Or can you think of a reason to keep it?

Cheers,

Matt

**Comment by fbiville** [comment]
Does this mean that Liquigraph will **always** resolve schemas offline? If so, sure, you can get rid of `RedirectAwareEntityResolver`.

**Comment by mattharr** [comment]
Hmm, good point.  No I think what I might do is chain the resolvers; I'll try the local file system one first, then if nothing from there use the redirect aware resolver.  That probably gives a more transparent resolution if other xsds are used.

**Comment by mattharr** [comment]
Hi, I've reset my fork, and made the changes there; that is, I've added the chained entity resolution and two resolvers.  I haven't fully dug into the test errors, but hopefully that just the windows problem.  Does this look ok?

**Comment by fbiville** [comment]
@mattharr would you mind opening a PR? I can take it from there.

**Comment by sey** [comment]
Just for information: @mattharr fork works with explicit schema validator but not with the implicit one.

**Comment by fbiville** [comment]
@sey Thanks for giving it a try! Would you be interested in contributing the missing part? I can help.

**Comment by sey** [comment]
I don't mind. I already tried. I wanted to add the same logic as what matt did with the resolvers but the `ImplicitSchemaValidator` is quite different. I was thinking setting a ResourceResolver on the validator would enable me to do the trick but it never gets called. So any hint would be appreciated.

**Comment by mattharr** [comment]
Hi, I've created PR #250, hopefully its usable.  I do vaguely remember looking at the implicit resolver, but left it because it looked more involved.  If I get a chance over the weekend I'll try have a look and see if I can do something about it - or at least provide some thoughts.

**Comment by hikemachado** [comment]
Very Nice Fix!
When do you expect to have a version for neo4j 3.x available in Maven Repository?

**Comment by fbiville** [comment]
> Very Nice Fix!
> When do you expect to have a version for neo4j 3.x available in Maven Repository?

Once I backport this change to 2.x and 4.x and I fix an unrelated CI issue, I'll release a new 2.x, 3.x and a first 4.x release candidate (within next week, hopefully).

**Comment by hikemachado** [comment]
> > Very Nice Fix!
> > When do you expect to have a version for neo4j 3.x available in Maven Repository?
> 
> Once I backport this change to 2.x and 4.x and I fix an unrelated CI issue, I'll release a new 2.x, 3.x and a first 4.x release candidate (within next week, hopefully).

Thanks a lot @fbiville , I started using this API this week. it's awesome. 
really nice work!

 Any one can contribute fixing issues? I`d like to contribute.

Awesome Project
Congratulations

**Comment by fbiville** [comment]
@hikemachado absolutely, if you have a particular issue in mind, let me know else I can try to find one for you :)

**Comment by hikemachado** [comment]
So, you can find one form me :) 
thanks

**Comment by fbiville** [comment]
@hikemachado feel free to pick an issue in the good first issues defined [here](https://github.com/liquigraph/liquigraph/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee). I can help you get started (easier to continue by Twitter or email for the next steps, though).

**Comment by ihordz** [comment]
@fbiville 
When it is planned to release version for 3.x branch with offline usage fix. Current one 3.1.1 does not include it.

**Comment by fbiville** [comment]
@ihordz I wanted to first update CI with Neo4j 3.4 and 3.5 but it has been quite challenging.
I can do a release today so that does not get dragged any longer

**Comment by fbiville** [comment]
@ihordz https://github.com/liquigraph/liquigraph/releases/tag/liquigraph-3.1.2 is now published (Maven Central repos are still syncing, but they will be probably be ready in a couple of hours with the 3.1.2 artifacts).

**Comment by ihordz** [comment]
@fbiville 
Thank you very much.
