### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mymac80** [liquigraph/liquigraph#249]
Hi,

Can we have a new release please? Hoping to get this bug fix in there: https://github.com/liquigraph/liquigraph/issues/220 that was merged by @fbiville a few weeks back.

Thanks!

**Comment by fbiville** [comment]
Yes, I will try to make some time this week.

**Comment by ctytgat** [comment]
Would be nice if that could also include #248  
(This is currently blocking upgrades to spring boot 2.2)

**Comment by oferbar** [comment]
There's another issue with the current release, since it's using an older version of Neo4j jdbc driver 3.1.0.
As we run Blackduck scans, we are getting security high risk errors.
So this library must be updated to the latest neo4j 3.4.0 if we want to keep on using it...
Thanks

**Comment by ctytgat** [comment]
@fbiville do you need help in creating a new release? 
This is currently blocking for us so we'll have to either abandon this library or fix it ourselves somehow  ...

**Comment by sey** [comment]
For info, the move to Neo4j JDBC 3.4.0 may have some impact on performance. It is great from a features (handling of dates) perspective (and security maybe). But the way the native driver is handled is not good. It basically creates a driver and a connection pool for every connection. And it closes the driver when closing the connection.

**Comment by fbiville** [comment]
> @fbiville do you need help in creating a new release?
> This is currently blocking for us so we'll have to either abandon this library or fix it ourselves somehow ...

Let me try to have a release this week, then.
I'll merge the offline support afterwards and re-release.

**Comment by oferbar** [comment]
> For info, the move to Neo4j JDBC 3.4.0 may have some impact on performance. It is great from a features (handling of dates) perspective (and security maybe). But the way the native driver is handled is not good. It basically creates a driver and a connection pool for every connection. And it closes the driver when closing the connection.

Hi,
Thanks for the information! 
Do you have any reference to that?
I'm interested to find out as we use the latest 3.x driver.
Thanks!

**Comment by sey** [comment]
Does my own reference count? https://github.com/neo4j-contrib/neo4j-jdbc/issues/212

**Comment by fbiville** [comment]
Doing the release now FYI.

**Comment by fbiville** [comment]
https://github.com/liquigraph/liquigraph/releases/tag/liquigraph-3.1.1 (indices in Maven Central will update soon-ish)

**Comment by ctytgat** [comment]
@fbiville thx. I was expecting this to fix also https://github.com/liquigraph/liquigraph/issues/248, but just saw that there is still no new jdbc driver available :(
