### ISSUE TITLE
[4.x] Support multiple graph database

### ISSUE THREAD

**Issue by maximus321** [liquigraph/liquigraph#370]
With [neo4j sdn-rx
](https://neo4j.github.io/sdn-rx/current/)

It is possible to have multiple segregated database, for example to support multi-tenancy.
Is it possible to support configuration that can handle multiple different database version? Would need to add a attribute "database" to specify on which database to run the migration.
I did not see any documentation or examples related to that.

Thanks!

**Comment by maximus321** [comment]
`Configuration configuration = new ConfigurationBuilder()
        .withMasterChangelogLocation("changelog.xml")
        .withUri("jdbc:neo4j:http://localhost:7474")
// TO-DO support database
.withDatabase("nameOfDatabase")
        .withRunMode()
        .build();
`

**Comment by fbiville** [comment]
Thanks for the report!
Let me ask the JDBC driver team whether that feature is supported.

**Comment by fbiville** [comment]
And it is: https://github.com/neo4j-contrib/neo4j-jdbc/tree/4.0#list-of-supported-neo4j-configuration-parameters (see the `database` parameter).
Let me know if you are interested in developing that feature, happy to offer guidance if needed.

**Comment by maximus321** [comment]
Sure Florent would be happy to contribute!
I'll clone the repo and start exploring the project, to see where this could be added
Any information appreciated

Un gros merci,
Max

**Comment by fbiville** [comment]
> Sure Florent would be happy to contribute!
> I'll clone the repo and start exploring the project, to see where this could be added
> Any information appreciated

Great! :)
As a starting point, the branch is `4.x`, not `master`.

## Liquigraph Core
The main classes impacted by this change are:

- [Configuration.java](https://github.com/liquigraph/liquigraph/blob/4.x/liquigraph-core/src/main/java/org/liquigraph/core/configuration/ConfigurationBuilder.java#L37)
- and its Builder companion [ConfigurationBuilder.java](https://github.com/liquigraph/liquigraph/blob/4.x/liquigraph-core/src/main/java/org/liquigraph/core/configuration/ConfigurationBuilder.java#L37)

in `liquigraph-core` module. You may want to add [some tests](https://github.com/liquigraph/liquigraph/blob/4.x/liquigraph-core/src/test/java/org/liquigraph/core/configuration/ConfigurationBuilderTest.java) around validation.

## Liquigraph Maven Plugin

Once that's done, the Maven plugin [base Mojo class](https://github.com/liquigraph/liquigraph/blob/4.x/liquigraph-maven-plugin/src/main/java/org/liquigraph/maven/LiquigraphMojoBase.java#L33) must be adapted as well to expose this new parameter and use it.

## Liquigraph CLI

Same idea as with the Maven plugin for the [CLI class](https://github.com/liquigraph/liquigraph/blob/master/liquigraph-cli/src/main/java/org/liquigraph/cli/LiquigraphCli.java#L41).

Let me know if I can help further!

**Comment by maximus321** [comment]
Thanks for the help Florent, 

I'm a bit noob with open-source, I get a 403 when trying to push to a feature branch to create a PR.
Is there something i'm missing? 

My idea was to connect using Properties instead of passing username and password 
i.e:
                return DriverManager.getConnection(uri, properties);

and construct this, eventually may want to support the other configuration if they are usefull for graph migration too.

```
   @Override
    public Connection get() {
        return connectionSupplier.getConnection(uri, properties);
    }
```

    // TODO - support all missing parameters here -
    // https://github.com/neo4j-contrib/neo4j-jdbc/tree/4.0#list-of-supported-neo4j-configuration-parameters
    private Properties buildProps() {

        Properties props = new Properties();
        username.ifPresent(user -> props.setProperty("user", user));
        password.ifPresent(pw -> props.setProperty("password", pw));
        props.setProperty("database", database.orElse("neo4j"));

        return props;
    }`

**Comment by maximus321** [comment]
Let me know if you can add me as contributor :)

Also, is this code still used?  uri not present? If not, could do a small cleanup meanwhile.
Merci!

`    private ConnectionConfiguration dataSourceConfiguration() {
        if (uri.isPresent()) {
            return new ConnectionConfigurationByUri(uri.get(), database, username, password);
        }
        return new ConnectionConfigurationByDataSource(dataSource.get(), username, password);
    }`

**Comment by maximus321** [comment]
Ok my local branch is ready to open PR, 

`    @Test
    public void should_use_default_database_if_database_not_provided() {

        Configuration configuration =  new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog/changelog.xml")
                .withUri("jdbc:neo4j:http://localhost:7474")
                .withUsername("steve")
                .withPassword("password")
                .withRunMode()
                .build();

        Neo4jConnection neo4jConnection = (Neo4jConnection) configuration.dataSourceConfiguration().get();
        Properties properties = neo4jConnection.getProperties();

        assertThat(properties.get("database"))
            .isSameAs("neo4j");
    }

    @Test
    public void should_use_database_if_provided() {

        Configuration configuration =  new ConfigurationBuilder()
                .withMasterChangelogLocation("changelog/changelog.xml")
                .withUri("jdbc:neo4j:http://localhost:7474")
                .withUsername("user")
                .withPassword("pw")
                .withDatabase("myDatabase")
                .withRunMode()
                .build();

        Neo4jConnection neo4jConnection = (Neo4jConnection) configuration.dataSourceConfiguration().get();
        Properties properties = neo4jConnection.getProperties();

        assertThat(properties.get("database"))
            .isSameAs("myDatabase");
    }`

**Comment by fbiville** [comment]
@maximus321 you need to fork this repository, add a new Git remote pointing to the fork repository, push there and open a new PR.

Regarding the other properties exposed by the JDBC driver, that's a very good point.
I think it would be a good idea to address that in a separate pull request.

**Comment by maximus321** [comment]
Thanks :)

Here is the PR:
https://github.com/liquigraph/liquigraph/pull/371/

May need some adjustment, feel free to comment

**Comment by fbiville** [comment]
4.0.1 release includes this change, thanks again: https://github.com/liquigraph/liquigraph/releases/tag/liquigraph-4.0.1

**Comment by maximus321** [comment]
Hey Florent,

Seems to be an issue with the latest release, the code is still ran against the default "neo4j" DB here.
Ill check to see if I can find why

`
  private final static String DATABASE = "myDB";

  public static void main(String[] args) {
    Configuration configuration = new ConfigurationBuilder()
            .withMasterChangelogLocation("changelog.xml")
            .withUri("jdbc:neo4j:http://localhost:7474")
            .withDatabase(DATABASE)
            .withUsername("neo4j")
            .withPassword("neo4j1")
            .withRunMode()
            .build();

    Liquigraph liquigraph = new Liquigraph();
    liquigraph.runMigrations(config`

**Comment by fbiville** [comment]
Hello @maximus321, I just tried again with the 4.0.1 release and it seems to work fine.
```java
import org.liquigraph.core.api.Liquigraph;
import org.liquigraph.core.configuration.Configuration;
import org.liquigraph.core.configuration.ConfigurationBuilder;

public class Test {

    public static void main(String[] args) {
        Configuration configuration = new ConfigurationBuilder()
        .withMasterChangelogLocation("changelog.xml")
        .withUri("jdbc:neo4j:bolt://localhost")
        .withUsername("neo4j")
        .withPassword("toto")
        .withDatabase("liquigraph2")
        .withRunMode()
        .build();

        new Liquigraph().runMigrations(configuration);
    }
}
```
I just alternated between databases `liquigraph1` and `liquigraph2` and everything went as expected. The default database `neo4j` remained untouched.

**Comment by fbiville** [comment]
Oh, but I used the Bolt driver. It seems multi-database is not supported by the HTTP driver. I'll double-check with the JDBC driver team.

**Comment by fbiville** [comment]
After a quick investigation, Neo4j does not support multi-database in the REST API so configuring a database in that context should trigger an error. I just created https://github.com/liquigraph/liquigraph/issues/379 and will release the fix hopefully soon.

**Comment by maximus321** [comment]
I confirm it works with the bolt URI instead, thanks !
