### ISSUE TITLE
How does versioning work?

### ISSUE THREAD

**Issue by gfitrz** [liquigraph/liquigraph#388]
Hey,
I have question about db versioning cause i didn't find it in documentation. 
How does versioning work? For example my changelog has a one changeset and I started liquigraph. If I run liquigraph once again, will it invoke changeset once again or maybe not? 

That what I want achieve is that to run every changeset only once, no matter how many I run liquigraph.  And when I add another changeset, it will invoke only the new one.

**Comment by fbiville** [comment]
Hi, 

Thanks for asking.

Versioning is documented in the detailed documentation (e.g. see the "Changeset incrementality" section in https://www.liquigraph.org/4.x/index.html).

In short, Liquigraph persists the changesets in the target graph database.
By default, changesets :
- are executed only once (they are incremental) 
- cannot be modified ever (they are immutable [checksum is persisted as well]) or Liquigraph will throw an error.

If a changeset needs to be run every time Liquigraph runs, you need to set `run-always="true"` as a changeset attribute (note: the changeset is still considered immutable).

If a changeset needs to be run whenever its content has been updated, you need to set `run-on-change="true"` as a changeset attribute.

If a changesets needs both, set both attributes.

Does that help?
How can we improve the documentation to make this clearer?

**Comment by gfitrz** [comment]
Hi, thank you for the answer.
Yes now I understand it. :) Hard to say how can you improve implementation but explanation like this would be good in it. It really makes things clearer,

**Comment by fbiville** [comment]
Thanks for the feedback. I'll work on [the docs](https://github.com/liquigraph/liquigraph.github.io/pull/6) today.

**Comment by fbiville** [comment]
I added a "Crash course" section at the beginning for each version:
- https://www.liquigraph.org/2.x/index.html
- https://www.liquigraph.org/3.x/index.html
- https://www.liquigraph.org/4.x/index.html
Feel free to reopen the issue if you think this can be further improved.
