### ISSUE TITLE
[4.x] Bolt+routing availability 

### ISSUE THREAD

**Issue by pelletier197** [liquigraph/liquigraph#398]
Hello,

I have a neo4j 4.0 application that needs to migrate a multi tenant database using liquigraph.

I am using the latest version of liquigraph (4.0.1), and there seems to be an issue when using bolt+routing protocol with this version.

I see that you fixed this issue really recently, but haven't yet released it. I hotfixed the issue on my side by copying all the configuration builder and skipping the validation of the URL, but I wanted to ask if you have any idea when the next release is planned to be done. 

Thank you for you help!

**Comment by fbiville** [comment]
Hello, I'll do it now :)
I wanted to wait for https://github.com/neo4j-contrib/neo4j-jdbc/pull/228 to be released, but I can do another release once it's available.

**Comment by pelletier197** [comment]
Wow that's awesome! Thank you 👌

**Comment by fbiville** [comment]
[The release is done](https://github.com/liquigraph/liquigraph/releases/tag/liquigraph-4.0.2), it will take an hour or so before it is available on Maven Central.
