### ISSUE TITLE
BeanCreationException error when database is unavailable

### ISSUE THREAD

**Issue by oferbar** [liquigraph/liquigraph#415]
We are using liquigraph in a Spring Boot application.
When the application is starting and Neo4j database is down or not available the application stops due to the - BeanCreationException.

Is there a way to to configure liquigraph not to fail and retry until the database is available?

**Comment by fbiville** [comment]
@oferbar there is no retry mechanism yet in Liquigraph, but that could be definitely useful (even in the core module!)

**Comment by fbiville** [comment]
A retry mechanism is planned for the JDBC driver (and this is something that will be used by the replacement of Liquigraph: https://github.com/liquibase/liquibase-neo4j) /cc @conker84
