### ISSUE TITLE
CLI: Only one version deployed

### ISSUE THREAD

**Issue by kristof-mattei** [liquigraph/liquigraph#423]
When the code gets built it only deploys the combination of neo4j and the driver specified in the initial `pom.xml` whereas the tests are run against a multitude of combinations.

I need a higher combination as for `3.x` the version deployed doesn't support `bolt+routing`, but there's a combination being built that does. Building that combination locally works perfectly.

Is there a reason these files aren't being published?

**Comment by fbiville** [comment]
Thanks for the report.
There is currently a fix in progress that makes the JDBC driver a runtime-scoped dependency (which should have been from the beginning 😅).

In general, setting the right version of the JDBC driver is a _consumer_ POM concern, in my opinion.
The CI just makes sure that the "official" Neo4j/JDBC version combinations do not blow up.

As for the CLI, that remains a good question. We could indeed publish a series of versions or find a way for CLI users to override the JDBC version easily.

**Comment by fbiville** [comment]
Feel free to reopen the issue if you have any question.
The JDBC driver dependency scope has been fixed in the latest release: https://github.com/liquibase/liquigraph/releases/tag/liquigraph-4.0.3
