### ISSUE TITLE
[4.x] Liquigraph changeset execution triggers  "Tried to execute Schema modification after executing Query"

### ISSUE THREAD

**Issue by JnMik** [liquigraph/liquigraph#424]
Hello guys ! 

```
<changeset id="some-id-1" author="author">
        <query>CREATE INDEX ... </query>
        <query>CREATE INDEX ... </query>
    </changeset>

    <changeset id="some-id-2" author="author">
        <query>
            CALL db.index.fulltext.createNodeIndex(...])
        </query>
        <query>CREATE INDEX ... </query>
    </changeset>
```

We have this 2 changesets following each other, and when Liquigraph try to execute the second one, we have this error:
**Tried to execute Schema modification after executing Query**

It seems to trigger the following Neo4j exception "Neo.ClientError.Transaction.ForbiddenDueToTransactionType"

_"The transaction is of the wrong type to service the request. For instance, a transaction that has had schema modifications performed in it cannot be used to subsequently perform data operations, and vice versa._

Is there a way to force Liquigraph to use a fresh connection on the second changeset so the query can be executed properly ? 

Thanks!

**Comment by fbiville** [comment]
Hi @JnMik, thanks for the report.

Liquigraph should already support this usecase (i.e. mixing some schema-related changesets and data-related ones).
It could be a regression.

What version and which module (core, Maven, CLI) are you using?

**Comment by JnMik** [comment]
We run Liquigraph with 4.0.2 core.

I  believe the issue occurs because we upgrade to Neo4j 4.1.1 !

**Comment by JnMik** [comment]
Do you plan supportin neo4j 4.1 anytime soon ? 
It seems the neo4j odbc driver you use is stuck in the past (4.0.x) :(

**Comment by pelletier197** [comment]
I debugged a little the problem, and it seems to be because that Neo4j 4.1.1 does not allow executing a query and schema modification inside a single transaction (I think). This seems to be undocumented in the change logs of Neo4j...

**Comment by fbiville** [comment]
A single transaction (which roughly translates to a Liquigraph changeset) can never mix schema and data operations, this is not a new limitation.
However, in the case above, there does not seem to be any mix of data/index write in any changeset, so it should work fine.
I'll try to find some time to reproduce the issue.

**Comment by pelletier197** [comment]
I digged a little more into this. Here's the changelog I used that should reproduce the error in `Neo4j 4.1.1-enterprise` 
```xml
    <changeset id="addFileSearchIndexes" author="sunny">
        <query>CREATE INDEX file_extension FOR (file:File) ON (file.extension)</query>
        <query>
            CALL db.index.fulltext.createNodeIndex("files", ["File"], ["path", "extension"])
        </query>
    </changeset>
```
Sadly, the `db.index.fulltext` is considered a query and not a schema modification query, which is okay. Note that this did not cause any problem before Neo4j 4.1.x in our case.

My solution was to put those two queries into different migration changesets
```xml
    <changeset id="addFileExtensionIndex" author="sunny">
        <query>CREATE INDEX file_extension FOR (file:File) ON (file.extension)</query>
    </changeset>

    <changeset id="createFileSearchIndex" author="sunny">
        <query>
            CALL db.index.fulltext.createNodeIndex("files", ["File"], ["path", "extension"])
        </query>
    </changeset>
```
which now works fine.

Now, if you consider this a bug, the solution I believe would be really simple: commit every query, instead of after all the queries 

Thus `ChangelogGraphWriter.executeChangesetQueries` becomes

```java
    private void executeChangesetQueries(Collection<String> queries) throws SQLException {
        try (Statement statement = writeConnection.createStatement()) {
            for (String query : queries) {
                statement.execute(query);
                LOGGER.debug("Executing query: {}", query);
                writeConnection.commit();
            }
            LOGGER.debug("Committing transaction");
        }
    }
```

I don't know if this solution may have side effects, so I leave it to you, but I hope this helps you. Thank you for your support!

**Comment by fbiville** [comment]
I see, it is all linked to `db.index.fulltext.createNodeIndex`, then.
I think that the solution of committing every query would not work as they would still be in the same transaction (JDBC Statement). Moving each query to its own separate transaction would break Liquigraph model, a failing query should cause the whole changeset to roll back.

I'll try to gather more information about transaction management and (built-in) procedures.

**Comment by fbiville** [comment]
If `db.index.fulltext.createNodeIndex` is indeed not a schema operation anymore, there is nothing else to do than move it to its separate change set.
