### ISSUE TITLE
Liquigraph does not seem to work with SDN/OGM

### ISSUE THREAD

**Issue by manuelprinz** [liquigraph/liquigraph#425]
First of all, thank you for providing Liquigraph to the graph community! :smiley: 

I tried it with the sample project provided, but unfortunately I was not able to get Liquigraph to work in a different Spring Boot 2 project using Spring Data Neo4j and the Liquigraph Spring Starter (3.1.2). I suspect that the problem is on my side but after several hours I am stuck.

My project uses Neo4j via SDN/OGM, auto-configured via `spring.data.neo4j.url: 'bolt://localhost:7687'` (YAML). It also uses PostreSQL via `spring-starter-jpa`, configured as `sping.datasource.url: 'jdbc:postgresql://localhost/postgres'`. This seems to be one of the problems, as Liquigraph tries to run the migrations against the PostgreSQL database.

Configuring `spring.liquigraph.url: 'jdbc:neo4j:bolt://localhost:7687'` does not seem to work. It stops connecting to PostgreSQL but fails because it cannot load the Native Types implementation. (Disabling them fails because I use native types.) Switching to the HTTP protocol does not seem to make a difference.

Can Liquibase use the SDN settings and configuration? Do I need other (redundant) configuration?

I tried adding a custom DataSource using the `@LiquigraphDataSource ` annotation but to no avail.

Any hints are very welcome! Please let me know if you need more information! Thanks in advance!

**Comment by fbiville** [comment]
Hi @manuelprinz, thanks for reporting this.
Would you happen to be able to share the application source code?
Adding SDN/OGM test applications in Liquigraph CI is definitely on the TODO list!

**Comment by manuelprinz** [comment]
Hi @fbiville, sorry for not getting back to you! I missed it and it fell through the cracks…

I just gave the issue another go and it seemed to work! I think I confused myself a bit there… I added the following configuration to `application.yml`:
```yaml
liquigraph:
  url: "jdbc:neo4j:${spring.data.neo4j.uri}"
  user: "${spring.data.neo4j.username}"
  password: "${spring.data.neo4j.password}"
```
Which seemed to work fine. This is reproducible on a small demo project (straight from Spring starter) with JPA and Neo4j enabled. If you configure e.g. JPA using Postgres and Neo4j via the SDN settings Liquigraph fails because it tries to send Cypher to Postgres which it does not like (for obvious reasons, although it might be nice to query it that way... :wink:). Configuring Liquigraph manually by passing the same settings as for SDN/OGM seems to work nicely.

However, I think it would still be an improvement if Liquigraph could detect that SDN is used (in Spring Boot) and automatically select the SDN settings when it loads, so that the Spring starter is a zero-configuration solution. It could still use the Liquigraph settings if one needs to do adjustments. I unfortunately lack the knowledge about what be needed to do that so I cannot provide a MR. If you have some pointers I could give it a try, though.

Also, it might be nice if Liquigraph could use OGM or the respective Neo4j driver instead of JDBC when using SDN since this bring in an extra dependency (JDBC) that might not be needed/wanted.

Thanks for your work and sorry about the unresponsiveness!

Best,
Manuel

**Comment by manuelprinz** [comment]
Small addendum: It (obviously) fails when using the embedded database in testing because that uses the native driver.

**Comment by fbiville** [comment]
@manuelprinz property reuse is indeed your best bet.
Since https://github.com/liquibase/liquibase-neo4j is available and replaces Liquigraph, I'm afraid this issue won't be worked on. Thanks for the great suggestion nonetheless!

**Comment by manuelprinz** [comment]
@fbiville, thank you very much for taking the time to reply! I will have a look at the Liquibase Neo4j plugin. Thank you for the pointer, I would have missed it!
