### ISSUE TITLE
Improve transaction handling for better robustness in error cases 

### ISSUE THREAD

**Issue by DirkMahler** [liquigraph/liquigraph#434]
We're running liquigraph during the startup of a (Spring based) microservice. We got issues when our infrastructure (for whatever reasons...) decided to kill the process while running the migrations. The effect that we see is that the actual content of a changeset is applied (e.g. creation of a constraint) but the changelog is not written.

For that reason it would be better to have the execution of the changeset and updating the changelog within the same transaction (as liquibase does). There might be a gap that not all applied changes are transactional but at least that makes the potential gap/inconcistency smaller.

This needs to be aligned with the (very useful!) post-condition mechanism but as far as I can judge it should be ok to update the changelog if an existing post-condition evaluates to false for the first time.

I could try to create a PR for this.

**Comment by fbiville** [comment]
Hi @DirkMahler, I'm in the process of deprecating Liquigraph in favor of https://github.com/liquibase/liquibase-neo4j, a native Liquibase plugin for Neo4j.
I currently need to finalize a migrator from Liquigraph to Liquibase, let me know if you want early access to this.

**Comment by DirkMahler** [comment]
Just noticed that creating a constraint & updating data (nodes/relations/properties) is not allowed by Neo4j within the same transaction. So using transactions to improve robustness in case of failure is not an applicable solution.

**Comment by fbiville** [comment]
Indeed, these need to be in separate transactions.

**Comment by DirkMahler** [comment]
We did a deeper investigation of the issue on our side and it turned out that things are a bit different than we thought initially:

We're using a Neo4j cluster and the master changed while trying to update the changelog. This ended up in an `SessionExpiredException` reporting that the master `no longer accepts writes`. 

According to https://github.com/neo4j/neo4j-java-driver/issues/522#issuecomment-409905703 this can be handled transparently by the underlying Neo4j driver if the transaction functions API is used: https://neo4j.com/docs/java-manual/current/session-api/simple/#java-driver-simple-transaction-fn.

As far as I can see liquigraph relies on the Neo4j JDBC driver and therefore probably has no direct control over this. I assume that it would be similar for the Liquibase approach?

**Comment by fbiville** [comment]
I recently worked on the JDBC driver to rely on transaction functions instead of raw `session.run`, but that has not been released yet.
I suppose the issue will be hard to reproduce, but does using the latest 4.0 https://github.com/neo4j-contrib/neo4j-jdbc help at all?

And by the way, you are 100% right, the Liquibase plugin relies on the same JDBC driver

**Comment by DirkMahler** [comment]
I'll try to reproduce the issue locally and check, if the JDBC snapshot fixes it. Should be possible to do it manually by juggling around with breakpoints and container startups/shutdowns.

**Comment by DirkMahler** [comment]
Good and bad news:

* Good News: I can reproduce the issue locally. 
  * Create a Neo4j cluster using Docker Compose according to https://neo4j.com/docs/operations-manual/current/docker/clustering/.
  * Add a break point in org.liquigraph.core.io.ChangelogGraphWriter#write right after executeStatement() and run the migration in the IDEs debugger
  * If the break point is reached, check in the Neo4j browser for the current leader (`:sysinfo`) and stop/start the container manually on the command line, this will cause a new leader to be elected
  * continue in the IDE with insertChangeset()
* Bad News: 
  * The problem is not solved by using the transactional functions (I cloned and built the current snapshot from the 4.0 branch of the Neo4j JDBC driver)
  * There's still the SessionExpiredException breaking the flow

**Comment by fbiville** [comment]
So, internally, it seems statements are not executed in transaction functions but in explicit transactions.
I need to confirm this, but I believe the retry mechanism is exercised only for transaction functions, not explicit transactions.
However, I'm quite confident that Spring Data Neo4j uses explicit transactions and implemented an [optional retry mechanism](https://github.com/spring-projects/spring-data-neo4j/blob/ea28dcadea3cd42196edca8e21f8faa00a69f73a/src/main/java/org/springframework/data/neo4j/core/support/RetryExceptionPredicate.java) so I could have a look at what they have done and try to implement it in the JDBC driver.

**Comment by DirkMahler** [comment]
I've played around a bit with the JDBC driver & Liquigraph. It seems that I could at least reduce probability of running into that problem by doing a little change to Liquigraph itself: 

Currently the write JDBC connection is kept as a field in the ChangelogGraphWriter. I removed it but instead now a "fresh" connection is acquired from the connectionSupplier for executing the changeset and updating the changelog.

Liquigraph build including tests is still green, so if you consider this acceptable then I'd prepare a PR for it (next week). The same approach should then be applied to Liquibase Neo4j as well.

**Comment by fbiville** [comment]
As long as we keep 1 transaction per change set, we can indeed break the single connection into several ones, I don't think that should be an issue 👍 
Please note that Liquigraph will go into minimal maintenance mode pretty soon.

I'll have to double-check how the Neo4j plugin for Liquibase behaves in the same scenario.

**Comment by DirkMahler** [comment]
PR #435 has been created,  the changes IMHO are straight forward and hopefully not too invasive.
