### ISSUE TITLE
Support for Gradle

### ISSUE THREAD

**Issue by mangrish** [liquigraph/liquigraph#55]
Are there any plans to do a native Gradle plugin for liquigraph or are you aware of one that someone has written? I couldn't find any through Google.

The product looks great and I'm tempted to use it but don't have time to trial and error a maven/cli gradle integration at the moment.

If you do plan to write one I see liquibase have written one which could be a good starting point: https://github.com/liquibase/liquibase-gradle-plugin

**Comment by fbiville** [comment]
Hey @mangrish, first of all, thanks for your feedback!

I've never been but an occasional basic user of Gradle and afaik, nobody has started working on a Gradle plugin.

If anyone is interested to go for it, then I'm very open to contributions.

I can start looking at this, but I cannot promise any deadline ;-)

**Comment by fbiville** [comment]
Good news: @diodfr is working on this 👍

**Comment by fbiville** [comment]
@diodfr any news about this? Feel free to send me your work if you don't think you will have time to continue ;-)

**Comment by fbiville** [comment]
Current work has been forked [here](https://github.com/fbiville/liquigraph-gradle-plugin). Anyone can start from there!

**Comment by fbiville** [comment]
We haven't been able to continue. Happy to re-open if someone is willing to take over the started work.
