### ISSUE TITLE
[Core] Spring-Boot Autoconfiguration module

### ISSUE THREAD

**Issue by mvitz** [liquigraph/liquigraph#99]
**This is mainly a marker issue for myself.**

In my current project I've written a spring-boot auto configuration which applies liquigraph migrations on application startup. I would contribute that code as a separate module once I find a little bit more time ;-)

**Comment by fbiville** [comment]
Ahah, super nice! Cannot wait for your PR :)

**Comment by fbiville** [comment]
It may be worth creating an extra module for that!

**Comment by fbiville** [comment]
How is it going? :-)

**Comment by mvitz** [comment]
I will try to push (at least a starting point) on the weekend. Currently I am very busy and not working in a Neo4j project any longer... :'(

**Comment by fbiville** [comment]
Hey there, would you mind publishing your work in progress somewhere?
For now, the integration with Spring Boot looks like this: https://github.com/fbiville/liquigraph-spring-boot-example.

**Comment by mvitz** [comment]
Thanks for pinging me again. I put it on my list somewhere near the top. Just give me a few more days. I will (as an example) fork your project and integrate it there.

**Comment by mvitz** [comment]
I put an initial version up at https://github.com/mvitz/spring-boot-starter-liquigraph and tried to use it with a branch of your example (https://github.com/mvitz/liquigraph-spring-boot-example/tree/spring-boot-starter-liquigraph).

Unfortunately currently it is not working because of some classloader stuff...

**Comment by fbiville** [comment]
The main change in Spring Boot 1.4 classloading is here: https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7.

However, I'm still not clear about what to do :(

**Comment by mvitz** [comment]
Just for discussion in https://github.com/mvitz/liquigraph/commit/aac4c2ef59de541519f1c3b9e2462c238c553b17 I added a new abstraction for loading changelogs. This is used by the spring-boot-starter in https://github.com/mvitz/spring-boot-starter-liquigraph/commit/e46b42227d081ef6ff383b8c27c6272c7d075e72 and when this version is used in the example https://github.com/mvitz/liquigraph-spring-boot-example/tree/spring-boot-starter-liquigraph everything works.

However introducing the `ChangelogLoader` is not fully backwards compatible.

**Comment by fbiville** [comment]
Maybe it's time to introduce a liquigraph-spring module? Cc @fpavageau

**Comment by mvitz** [comment]
I'm not sure this is needed. All classes I would put into this right now are https://github.com/mvitz/spring-boot-starter-liquigraph/blob/master/src/main/java/de/mvitz/liquigraph/spring/SpringLiquigraph.java and https://github.com/mvitz/spring-boot-starter-liquigraph/blob/master/src/main/java/de/mvitz/liquigraph/spring/SpringChangelogLoader.java

**Comment by fbiville** [comment]
Fetching directly Spring Framework into Liquigraph Core is undesirable in my opinion.
I don't mind creating tiny Maven modules :-)

**Comment by mvitz** [comment]
I'm not sure what we're talking about here.

My change in liquigraph-core just adds a new abstraction for loading changelogs instead of using a `ClassLoader` directly. By default there is an implementation in the core which delegates to the same `ClassLoader` that is used before. No dependency to spring is added by this change. The only thing that is not backwards compatible is that `Configuration` has a method `classLoader()` which now returns `null` if a `ChangelogLoader`-Implementation is used that doesn't use a `ClassLoader`...

My separate spring starter module contains another implementation which uses springs `ResourceLoader` instead of the `ClassLoader`.

With this changes the example stated above can use the starter and everything works as expected. I'm unsure how we should proceed from here ;-)

**Comment by fbiville** [comment]
Ok, my bad, I read too fast. Let me take some time to think this through.

**Comment by fbiville** [comment]
@mvitz I have taken some time to review the changes and that looks very good to me! Go go go! :-)
@fpavageau we should define a sensible deprecation policy by the way

**Comment by fbiville** [comment]
@mvitz do you need other elements from us? I think it's a go on our side.

**Comment by mvitz** [comment]
I only need some spare time to create the PR for the ClassLoader stuff ;-)

Another question is if the spring-boot-starter should become a module in this repo.

**Comment by fbiville** [comment]
If it can be a module of this project without too much hassle, it would be great!

**Comment by mvitz** [comment]
Ok, I will prepare a PR this or in the next week for both.

**Comment by fbiville** [comment]
Congratulations, it is now merged :champagne:

**Comment by fbiville** [comment]
Reopening, as we need to add some doc to http://fbiville.github.io/liquigraph/latest/index.html ^^
@mvitz would you have some time to do it? Everything is in plain HTML in `gh-pages` branch.

**Comment by fbiville** [comment]
Documentation added: http://fbiville.github.io/liquigraph/latest/index.html#spring-boot.
The only remaining part is the detailed documentation page. It should probably be a separate document.

**Comment by fbiville** [comment]
@mvitz I'm open for feedback on the small section I added, btw. (cc @fpavageau)

**Comment by mvitz** [comment]
Sorry I'm in vacation right now and don't have much time ;-)

I will add a MR next week with some slight enhancements but as a starting point this will work.

Notes:
- @EnableAutoConfiguration is normally not needed because @SpringBootApplication is used.
- Location of the change log can be changed this should be documented
- Configuration of the datasource can be done by simply using the default configuration as stated in https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-sql.html#boot-features-connect-to-production-database

**Comment by fbiville** [comment]
@mvitz thanks for the feedback. I think I'll wait for your update on the docs before releasing. You know that part better than me.

**Comment by fbiville** [comment]
Hi @mvitz, sorry to be a bit pushy about this, but people are already trying to use the Spring Boot module and clearly the docs are not in a good enough shape. If you could complete them soon, it would be awesome ;-)

**Comment by fbiville** [comment]
I think this is done :)
